version: "3"
services:
  app:
    container_name: nodejs
    restart: always
    build: .
    volumes:  
      - .:/app
    working_dir: /app
    ports:
      - "80:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
   mongodata: