version: "3"
services:
  app:
    container_name: nodejs
    restart: always
    build: .
    working_dir: /app
    volumes:  
      - .:/app
    ports:
      - "80:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
      - "./mongo:/docker-entrypoint-initdb.d"
    ports:
      - "27017:27017"
    environment:
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
volumes:
    mongodata: